### PR TITLE
Add go 1.17.x to the matrix build

### PR DESCRIPTION
**Pull request by kishaningithub**

### CODE REVIEW

**Comment by kishaningithub** [comment]
When i ran this in my local with go 1.17 gofmt did not produce any error though. Any clues?

**Comment by kishaningithub** [comment]
Checked this with the docker container as well. (Screenshot below)

Screenshot 2021-08-30 at 10 28 19 AM

**Comment by codyoss** [comment]
Hey @kishaningithub Thanks for the PR. This is due to changes in how build constants are described in newer versions of Go. If you run `goimports -w .` from the repo root I think that should apply all the corrections needed. (Assuming you have 1.17 installed). Also would you mind removing 1.16 from the matrix. I think it is fine to test the oldest version we are compatible with and the latest.

**Review by codyoss — CHANGES_REQUESTED** [review]
See comment above

**Comment by codyoss** [comment]
Close this PR, I will add 1.17 when I have the chance.

**Pull request closed without merging**
