### PR TITLE
Ignore stdout does not matter when decoding pkg content

### PR DESCRIPTION
**Pull request by yutianwu**
Hi, I have encountered the same problem described in https://github.com/golang/mock/issues/31. 

When I use gomock to generate code and if there is anything else printed to stdout, the program will complain "Loading input failed: extra data in buffer". 

IMO, Gomock is the best mock tool so far, and I do need it urgently. But I cannot use it when some other pkgs print stuff to stdout. I have done a little modification to ignore stdout that I don't need. 

I can use it now but I will appreciate it if you can merge my pr then I don't need to maintain my fork any longer. 

thx for you time~

### CODE REVIEW

**Comment by yutianwu** [comment]
I signed

**Comment by yutianwu** [comment]
I updated my profile

**Comment by yutianwu** [comment]
Done

**Comment by balshetzer** [comment]
@yutianwu 

I made some changes and posted it at #176. Could you please post on #176 that you consent to submitting this code? 

Thanks.

**Comment by balshetzer** [comment]
The purpose of this change is to handle the case where something is written to stdout on init(). Nothing else in the program is run besides the init.

If the package starts goroutines on init() which randomly write to stdout then we are in trouble. Writing to stdout is not synchronized so trying to write an entire buffer at once or putting sentinels before and after the content will not protect us from pollution.

**Comment by yutianwu** [comment]
Agreed, but I did encountered such a problem that goroutines of other packages written something to stdout after we print the indicator because we need a little time to generate pkg content and it happens all the time.
We cannot solve all problems with two indicators as you said but it helps sometimes.

**Comment by balshetzer** [comment]
If that's the case then I'd rather have the program write the output to a file in the temporary directory and read the output from there. This should always work.

**Comment by yutianwu** [comment]
Yeah, I thought about that. If you agree to do that, I'd be glad to do it and then there will be no problems.

**Comment by yutianwu** [comment]
@balshetzer 
Hi, I'm glad that you agree to write pkg content to temporary file, I have done some changes and could you please review it. Thank you very much

**Comment by balshetzer** [comment]
I addressed this issue with #184

**Pull request closed without merging**
