### PR TITLE
Tidy up module dependencies

### PR DESCRIPTION
**Pull request by kishaningithub**
My builds run on a network which blocks `google.golang.org/appengine v1.5.0` 
This PR is a result of running `go mod tidy` on this project. 

It would really be awesome if this project does not depend on appengine.

### CODE REVIEW

**Comment by kishaningithub** [comment]
I signed it!

**Comment by kishaningithub** [comment]
This is preventing us from migrating to `1.3.0`

**Comment by poy** [comment]
@kishaningithub I'll create a `1.3.1` tag

**Comment by kishaningithub** [comment]
@poy The upgrade is failing like

```
go: finding github.com/golang/mock v1.3.1
go: github.com/golang/mock@v1.3.1: unknown revision v1.3.1
go: error loading module requirements
```

The problem i saw was the git tag for the new version is `1.3.1` instead of `v1.3.1` (You accidentally Missed the v there)

Screenshot 2019-05-09 at 11 12 58 AM

**Pull request merged**
