### PR TITLE
Retrieve embedded interface that are imported from another package.

### LINKED ISSUE #10: mockgen chokes on embedded interfaces
I was able to reduce my problem to this minimal case:

```go
package test

import (
    "io"
)

type Iface interface {
    io.WriteCloser
}
```

Then mockgen fails:

```shell
$ $GOPATH/bin/mockgen -source iface.go -package test
2015/09/18 12:16:35 Loading input failed: iface.go:8:5: unknown embedded interface io.WriteCloser
$ $GOPATH/bin/mockgen -imports io=io -source iface.go -package test
2015/09/18 12:16:23 Loading input failed: iface.go:8:5: unknown embedded interface io.WriteCloser
```

Thanks for looking into the issue

### PR DESCRIPTION
**Pull request by fische**
* When an interface from an imported package is embedded, it parses this package to retrieve all its interfaces declarations and retrieves the appropriate interface to build the mock.
* Interfaces declared in auxiliary files take precedence over those from the imported package.
* Supports `vendor/` directory.
* This fixes #10.

### CODE REVIEW

**Comment by fische** [comment]
I signed it!

**Comment by rmohr** [comment]
@fische very nice! since I can't use the reflect mode like suggested in #10, your commits were very helpful.

@dsymonds any chance we can help you (verification, ...) to get some of the pull requests merged?

**Comment by c4milo** [comment]
I'm blocked by this as well. This PR fixes it for me @fische. Thanks!

Can we allow more maintainers here @dsymonds? This project needs more active maintenance. cc: @rakyll

**Comment by mikevel** [comment]
I'm blocked on this as well. @dsymonds @rakyll any chance to get this merged?

**Comment by marten-seemann** [comment]
@balshetzer @rakyll @dsymonds  Any plans to merge this some time soon?

**Comment by rakyll** [comment]
cc @broady and @zombiezen

**Comment by mikevel** [comment]
@balshetzer can you please comment?

**Comment by balshetzer** [comment]
I'd need this to be updated so that the conflicts are resolved and the continuous build passes.

**Comment by fische** [comment]
Sure. I will fix this as soon as possible.

**Comment by fische** [comment]
Done. Ping @balshetzer

**Pull request merged**
