### PR TITLE
feat: support embedded generic interfaces

### LINKED ISSUE #668: [mockgen] Errors creating mocks for embedded generic interfaces
I installed commit `73266f9366fcf2ccef0b880618e5a9266e4136f4` and attempted to generate mocks for an interface that uses both generics and embedded interfaces.  

Below is an example:

```go
type Foo[V any] interface {
	Method() V
}

type Bar[V any] interface {
	Foo[V]
	NewMethod() V
}
```

```
$ mockgen -source=input.go -destination=input_mockgen.go
2022/08/02 21:35:00 Loading input failed: don't know how to mock method of type *ast.IndexExpr
```

If I remove the interface embed from `Bar` the mocks will be generated.

**Additional Information**

-   gomock mode (reflect or source): source
-   gomock version or git ref: 73266f9366fcf2ccef0b880618e5a9266e4136f4
-   golang version: 1.18.1

**Triage Notes for the Maintainers**

### PR DESCRIPTION
**Pull request by tra4less**
fixes #668 #658 #700

### CODE REVIEW

**Comment by n0trace** [comment]
If not indented diff @codyoss 
```diff
index 21c0d70..7eae9c9 100644
--- a/mockgen/parse.go
+++ b/mockgen/parse.go
@@ -288,10 +288,19 @@ func (p *fileParser) parseInterface(name, pkg string, it *namedInterface) (*mode
 	}
 
 	for _, field := range it.it.Methods.List {
-		switch v := field.Type.(type) {
+		if err = p.parseField(field, field.Type, iface, pkg, tps); err != nil {
+			return nil, err
+		}
+	}
+	return iface, nil
+}
+
+func (p *fileParser) parseField(field *ast.Field, fieldType ast.Expr, iface *model.Interface, pkg string, tps map[string]bool) error {
+	{
+		switch v := fieldType.(type) {
 		case *ast.FuncType:
 			if nn := len(field.Names); nn != 1 {
-				return nil, fmt.Errorf("expected one name for interface %v, got %d", iface.Name, nn)
+				return fmt.Errorf("expected one name for interface %v, got %d", iface.Name, nn)
 			}
 			m := &model.Method{
 				Name: field.Names[0].String(),
@@ -299,7 +308,7 @@ func (p *fileParser) parseInterface(name, pkg string, it *namedInterface) (*mode
 			var err error
 			m.In, m.Variadic, m.Out, err = p.parseFunc(pkg, v, tps)
 			if err != nil {
-				return nil, err
+				return err
 			}
 			iface.AddMethod(m)
 		case *ast.Ident:
@@ -314,7 +323,7 @@ func (p *fileParser) parseInterface(name, pkg string, it *namedInterface) (*mode
 				var err error
 				embeddedIface, err = p.parseInterface(v.String(), pkg, embeddedIfaceType)
 				if err != nil {
-					return nil, err
+					return err
 				}
 			} else {
 				// This is built-in error interface.
@@ -323,16 +332,16 @@ func (p *fileParser) parseInterface(name, pkg string, it *namedInterface) (*mode
 				} else {
 					ip, err := p.parsePackage(pkg)
 					if err != nil {
-						return nil, p.errorf(v.Pos(), "could not parse package %s: %v", pkg, err)
+						return p.errorf(v.Pos(), "could not parse package %s: %v", pkg, err)
 					}
 
 					if embeddedIfaceType = ip.importedInterfaces.Get(pkg, v.String()); embeddedIfaceType == nil {
-						return nil, p.errorf(v.Pos(), "unknown embedded interface %s.%s", pkg, v.String())
+						return p.errorf(v.Pos(), "unknown embedded interface %s.%s", pkg, v.String())
 					}
 
 					embeddedIface, err = ip.parseInterface(v.String(), pkg, embeddedIfaceType)
 					if err != nil {
-						return nil, err
+						return err
 					}
 				}
 			}
@@ -345,7 +354,7 @@ func (p *fileParser) parseInterface(name, pkg string, it *namedInterface) (*mode
 			filePkg, sel := v.X.(*ast.Ident).String(), v.Sel.String()
 			embeddedPkg, ok := p.imports[filePkg]
 			if !ok {
-				return nil, p.errorf(v.X.Pos(), "unknown package %s", filePkg)
+				return p.errorf(v.X.Pos(), "unknown package %s", filePkg)
 			}
 
 			var embeddedIface *model.Interface
@@ -354,7 +363,7 @@ func (p *fileParser) parseInterface(name, pkg string, it *namedInterface) (*mode
 			if embeddedIfaceType != nil {
 				embeddedIface, err = p.parseInterface(sel, filePkg, embeddedIfaceType)
 				if err != nil {
-					return nil, err
+					return err
 				}
 			} else {
 				path := embeddedPkg.Path()
@@ -362,7 +371,7 @@ func (p *fileParser) parseInterface(name, pkg string, it *namedInterface) (*mode
 				if parser == nil {
 					ip, err := p.parsePackage(path)
 					if err != nil {
-						return nil, p.errorf(v.Pos(), "could not parse package %s: %v", path, err)
+						return p.errorf(v.Pos(), "could not parse package %s: %v", path, err)
 					}
 					parser = ip
 					p.imports[filePkg] = importedPkg{
@@ -371,11 +380,11 @@ func (p *fileParser) parseInterface(name, pkg string, it *namedInterface) (*mode
 					}
 				}
 				if embeddedIfaceType = parser.importedInterfaces.Get(path, sel); embeddedIfaceType == nil {
-					return nil, p.errorf(v.Pos(), "unknown embedded interface %s.%s", path, sel)
+					return p.errorf(v.Pos(), "unknown embedded interface %s.%s", path, sel)
 				}
 				embeddedIface, err = parser.parseInterface(sel, path, embeddedIfaceType)
 				if err != nil {
-					return nil, err
+					return err
 				}
 			}
 			// Copy the methods.
@@ -383,11 +392,25 @@ func (p *fileParser) parseInterface(name, pkg string, it *namedInterface) (*mode
 			for _, m := range embeddedIface.Methods {
 				iface.AddMethod(m)
 			}
+		case *ast.IndexExpr:
+			switch vv := v.X.(type) {
+			case *ast.SelectorExpr:
+				if err := p.parseField(nil, vv, iface, pkg, tps); err != nil {
+					return err
+				}
+			case *ast.Ident:
+				if err := p.parseField(nil, vv, iface, pkg, tps); err != nil {
+					return err
+				}
+			default:
+				return fmt.Errorf("don't know how to mock method of type %T", field.Type)
+			}
+
 		default:
-			return nil, fmt.Errorf("don't know how to mock method of type %T", field.Type)
+			return fmt.Errorf("don't know how to mock method of type %T", field.Type)
 		}
 	}
-	return iface, nil
+	return nil
 }
 
 func (p *fileParser) parseFunc(pkg string, f *ast.FuncType, tps map[string]bool) (inParam []*model.Parameter, variadic *model.Parameter, outParam []*model.Parameter, err error) {
```

**Comment by codyoss** [comment]
@n0trace Thanks for the PR! Would you be willing to expand support for this test case as well:

```
type EmbeddingIface interface {
	TwentyOne[other.Three]
	other.Twenty[StructType]
	Foo() error
}
```

If you don't have the time I can review this as is and this could be done in another PR.

**Comment by n0trace** [comment]
> 

done

**Comment by n0trace** [comment]
> @n0trace Thanks for the PR! Would you be willing to expand support for this test case as well:
> 
> ```
> type EmbeddingIface interface {
> 	TwentyOne[other.Three]
> 	other.Twenty[StructType]
> 	Foo() error
> }
> ```
> 
> If you don't have the time I can review this as is and this could be done in another PR.

done

**Comment by codyoss** [comment]
@n0trace Sorry if I was not clear, I meant just copy paste that code literally into generics.go. I don't think this solution covers the case where the outer interface does not contain type parameters, but the inner impl does.

**Comment by n0trace** [comment]
cases are complex than I have imagined, but done. please review. @codyoss

**Comment by n0trace** [comment]
fixes #658

**Comment by codyoss** [comment]
@n0trace I will take a look over the weekend, thank you!

**Comment by n0trace** [comment]
> @n0trace I will take a look over the weekend, thank you!
> 

cc @codyoss

**Comment by alexandreLamarre** [comment]
As a heads up this also fixes the same issue we were seeing in #658

**Comment by codyoss** [comment]
Reviewing this today, sorry. Had gotten pulled away from this project for awhile!

**Comment by codyoss** [comment]
@n0trace I am still digging through the code, but would you mind adding some docs around the new types/fields/methods you added. I know parsing code is lacking this in general right now, but since this adds a bit of complexity it would be nice to have so details of what/how things are being used.

**Comment by n0trace** [comment]
@codyoss added some comments.

**Comment by lennycampino** [comment]
@n0trace @codyoss Is there any update on this? :)

**Comment by hirikarate** [comment]
I'm having the same issue and I'm hoping this fix could make it to official as soon as possible.
Thank you all for the great work.

**Comment by n0trace** [comment]
@codyoss   Could you please review this pull request?

**Comment by chkp-omris** [comment]
I'm also having the same issue, could you please review this?

**Comment by tofluid** [comment]
This is needed, please review. Thanks!

**Comment by n0trace** [comment]
@codyoss  we need a resolution for mock generics. please review.

**Comment by paprikati** [comment]
We are also blocked on this - would love if we could use this ❤️

**Comment by AyushG3112** [comment]
@n0trace @codyoss any update on this please?

**Comment by samvdb** [comment]
Thanks for the pull request. Support for generics would be most welcome! Any update?

**Comment by n0trace** [comment]
Hi @codyoss ,

Thank you for taking the time to review my PR. I know you're busy, but this PR is important to me and I'm eager to have it reviewed as soon as possible.

I believe this PR adds value to the project by addressing embedded generic interfaces. If you need more information or clarification, please let me know and I'll be happy to provide it.

May I please ask for an update on the status of this PR? Do you need me to make any changes or provide additional information?

Thank you again for your time and consideration. I look forward to hearing back from you.

**Comment by samvdb** [comment]
I tested this PR with go version go1.20.1 linux/amd64 and can confirm generics are working.

**Comment by tofluid** [comment]
@codyoss or anyone else that can approve this PR. My team is really getting hamstrung and we're now starting to consider a different mocking library for go but then that'll be two testing standards which I do not want.

Please get this approved!

**Comment by colinschoen** [comment]
@codyoss Can you please have a look at this

**Comment by tedkornish** [comment]
Also eagerly awaiting this.

**Comment by maestre3d** [comment]
Just looked at Cody's LinkedIn profile. Looks like he got promoved and is no longer part of Google's Golang Developer Relations team.

I think we should ping another person to get this PR merged.

**Pull request closed without merging**
