### PR TITLE
Always remove self_package import

### PR DESCRIPTION
**Pull request by linzhp**
When users provide `-self_package`, gomock should always exclude that import from generated mock. The `pkg.Name` can be incorrectly determined in reflect mode:
 https://github.com/golang/mock/blob/0b73a1dbc3e1197079e9b9db31ab2879a5c9a095/mockgen/reflect.go#L206-L211

We should not reset `outputPackagePath` when it is passed from `-self_package`.

Fixing #342

### CODE REVIEW

**Comment by codyoss** [comment]
Not sure why this is working on CI, but if you run `go install ./... && ./ci/check_go_generate.sh` locally this fails.

**Comment by codyoss** [comment]
This may having nothing to do with this PR btw, but would like to get it fixed before evaluating further PRs.

**Comment by codyoss** [comment]
@linzhp thanks for your patience. I wanted to make sure we got our build properly working on master before we accepted any more PRs. Would you mind rebasing this as there are now some conflicts.

**Comment by linzhp** [comment]
@codyoss rebased

**Comment by linzhp** [comment]
Are you planning another release soon? It's been 8 months

**Comment by codyoss** [comment]
Yes, originally planned for tomorrow: https://github.com/golang/mock/milestone/1
Should land sometime this week. This package recently switched maintainers, so there was a bit of a lull.

**Comment by codyoss** [comment]
@linzhp One more thing, would you mind adding a testcase under `mockgen/internal/tests`. All it would need to be is a source file with a `go: generate` directive and the generated code. Our ci will try to regenerate all these and check for diffs to make sure this does not break again in the future.

**Comment by linzhp** [comment]
@codyoss Added a test case

**Comment by codyoss** [comment]
@linzhp Thank you for your patience and contribution! Should have this rolled up in a release later this week 🎆

**Pull request merged**
