### PR TITLE
Fix resolution of embedded interfaces in aux files

### PR DESCRIPTION
**Pull request by notbdu**
Embedded interfaces in `aux_files` generate `unknown embedded interface XXX` errors.
See below for example of the problem:
```
// source
import (
    alias "some.org/package/imported"
)

type Source interface {
    alias.Foreign
}
```

```
// some.org/package/imported
type Foreign interface {
    Embedded
}

type Embedded interface {}
```

Attempting to generate a mock will result in an `unknown embedded interface Embedded`.
The issue is that the `fileParser` stores `auxInterfaces` underneath the package name
explicitly specified in the `aux_files` flag.

In the `parseInterface` method, there is an incorrect assumption about an embedded interface
always being in the source file.
```
case *ast.Ident:
        // Embedded interface in this package.
        ei := p.auxInterfaces[""][v.String()]
        if ei == nil {
                return nil, p.errorf(v.Pos(), "unknown embedded interface %s", v.String())
        }
```

Test case verifies that the patch fixes the problem described in the bug report.

### CODE REVIEW

**Comment by pasztorpisti** [comment]
seems to be related to https://github.com/golang/mock/issues/85

**Comment by notbdu** [comment]
@pasztorpisti thanks for referencing those issues

**Comment by wsong** [comment]
This PR breaks this repo on Windows; `aux` is not a valid directory name in Windows (https://social.technet.microsoft.com/Forums/Azure/en-US/d1cf7394-a39b-46bf-823d-46f33b2f78d0/unable-to-create-folder-named-aux-anywhere-in-the-disk?forum=w7itprogeneral), so this PR prevents you from checking out this repo on a Windows machine.

**Comment by notbdu** [comment]
@wsong thanks for bringing it up. Opened a second PR w/ `aux` renamed to `faux`.

**Pull request merged**
