### PR TITLE
Support type-safe return values

### PR DESCRIPTION
**Pull request by tra4less**

### CODE REVIEW

**Comment by n0trace** [comment]
#622 #427

**Comment by danielvladco** [comment]
Hi, is there any progress on this PR?

**Comment by falsaffa** [comment]
Hey, any updates here? 

cc @codyoss

**Comment by falsaffa** [comment]
Hey @codyoss , is there anything @n0trace/we/anyone can do to help get this PR reviewed and approved?

**Comment by n0trace** [comment]
The implementation changed, by adding a flag. @codyoss @Trim21 
reference #622

**Comment by Trim21** [comment]
add new flag in readme？

**Comment by falsaffa** [comment]
@codyoss @n0trace any progress with the PR?

**Comment by n0trace** [comment]
cc @codyoss

**Comment by rekby** [comment]
@codyoss Is any ETA for review of the PR?

**Comment by jhalterman** [comment]
Would love to see this reviewed. Putting the feature behind a new flag seems like a good way to introduce it.

**Comment by alvarotuso** [comment]
Bump. This would be very useful.

**Comment by trim21** [comment]
cc @codyoss

**Comment by skynet2** [comment]
hi @n0trace , this also requires one additional fix for optional vars.

Example interface:
```go 
import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

type s3Client interface {
	HeadBucket(ctx context.Context, input *s3.HeadBucketInput, opts ...func(*s3.Options)) (*s3.HeadBucketOutput, error)
}
```
will generate incorrect mock Return func:
image
fix is https://github.com/skynet2/mock/commit/ca75ee65a535230e0f517a626f35d48646b50d0b 
image

Thanks

**Comment by trim21** [comment]
@codyoss can anyone review this PR?

**Pull request closed without merging**
