### PR TITLE
Adds a customizable matcher

### PR DESCRIPTION
**Pull request by rubens21**
Helps cases like #351. 

**Description**

This PR creates a customizable matcher that uses a custom function to evaluate the value. 

**Release Notes**

Improved API for custom matchers 

`I know that release note was an example, but that was exactly what this PR did!`

### CODE REVIEW

**Comment by rubens21** [comment]
@googlebot I signed it!

**Comment by codyoss** [comment]
@rubens21 Thanks for the PR, but this is not actually necessary. [Matcher](https://pkg.go.dev/github.com/golang/mock/gomock#Matcher) is already an interface that anyone can implement. You can define your own matchers in our codebase today and pass them in.

If you think this is not known today I think maybe we need to add some more/better docs around this. Can you open up an issue for that?

**Comment by rubens21** [comment]
> @rubens21 Thanks for the PR, but this is not actually necessary. [Matcher](https://pkg.go.dev/github.com/golang/mock/gomock#Matcher) is already an interface that anyone can implement. You can define your own matchers in our codebase today and pass them in.
> 
> If you think this is not known today I think maybe we need to add some more/better docs around this. Can you open up an issue for that?

Hi @codyoss , yeah I know anyone can implement that interface, and sometimes it is not a big deal.

However, many times implementing an interface (struct and two methods) to test a simple field is a painful work for a simple task. Having a shortcut to simplify that to a function could be handy.

Please consider to re-think about the advantage vs disadvantage of merging that. I have been used gomock for a couple of years already, and I used that matcher in almost all my projects.

**Comment by codyoss** [comment]
I have thought about this and think this is better solved by documentation.

**Pull request closed without merging**
