### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by szh**
Removes dependencies on "golang.org/x/net" package version with security vulnerability (https://github.com/golang/go/issues/50058).
This will fix projects depending on this package from being flagged by security scanners such as Snyk.

### CODE REVIEW

**Comment by codyoss** [comment]
@szh could you please sign the CLA

**Comment by szh** [comment]
@codyoss Sorry for the delay. Working through this with legal.

**Comment by codyoss** [comment]
@szh No worries. If it does not work out lmk and I can make a similar PR to get things updated. This might be a good time to prep for a next release and stop supporting older Go versions.(Updating to head dependencies may force this)

**Comment by szh** [comment]
@codyoss Honestly the sooner this is fixed the better. If it'll be faster for you to do it that's better for me too.

**Comment by codyoss** [comment]
Sounds good, I will try to get something out soon. Closing.

**Comment by codyoss** [comment]
#611 has landed on HEAD.

**Pull request closed without merging**
