### PR TITLE
add support for generics for source mode

### PR DESCRIPTION
**Pull request by codyoss**
Updates: #621

### CODE REVIEW

**Comment by codyoss** [comment]
Needs a bunch of tests and things still, but should not take too much more to get this working fully

**Comment by codyoss** [comment]
Also, still need to look into reflect support.

**Comment by omichels** [comment]
i have tried to use this fork but found out that the generated mocks are simply missing the type information

**Comment by codyoss** [comment]
@omichels It is still a WIP progress ATM, but getting closer. I have not committed everything yet either. I will ping on the linked issue when I think the PR is in a good state and see if anyone is still having issues. Thanks for being an early tester though!

**Comment by codyoss** [comment]
@omichels Would you mind trying again to see if you are still seeing issues?

**Comment by omichels** [comment]
> @omichels Would you mind trying again to see if you are still seeing issues?

Looks fine now. Thank you so much.


This is our use case:

"our" API, which we want to mock:
```
type ResourceGroupClient interface {
  NewListPager(options *armresources.ResourceGroupsClientListOptions) *runtime.Pager[armresources.ResourceGroupsClientListResponse]
}
```

Azure sdk:
```
type Pager[T any] struct {
	current   *T
	processor PageProcessor[T]
	firstPage bool
}

type PageProcessor[T any] struct {
	More func(T) bool
	Fetcher func(context.Context, *T) (T, error)
}
```

**Comment by steve-gray** [comment]
Hey @codyoss  - Keen to give this a spin as we're being burned with some code changes - in essence we can't regenerate mocks on some services now as a common package we have uses generics internally. 

When I try to install with the CLI, it bombs out due to the go.mod paths not matching - there a way to force the install?

``` 
go install github.com/codyoss/mock/mockgen@891f4736814577b05df08811fd90798a66bdde38


go: github.com/codyoss/mock/mockgen@891f4736814577b05df08811fd90798a66bdde38: github.com/codyoss/mock@v1.6.1-0.20220506173251-891f47368145: parsing go.mod:
        module declares its path as: github.com/golang/mock
                but was required as: github.com/codyoss/mock
```

**Comment by codyoss** [comment]
@steve-gray I don' think you can go install from a fork, but I could be wrong. You should be able to check out this code locally though and run `go install ./...` to build from source. Let me know how that works for you

As a side not I do plan on trying to get at least this PR merged sometime this week. But there are still likely a couple of edge cases and reflect mode support before I officially cut a release.

**Comment by steve-gray** [comment]
Seems to quietly do its thing without erroring, tests are running again. Cheers @codyoss  - I'll keep an eye out for the full release 🚀

**Comment by opannapo** [comment]
Thanks a lot suhu

**Pull request merged**
